// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/finance/v1/finance.proto

package financev1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _finance_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on PspConfig with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PspConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PspConfig with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PspConfigMultiError, or nil
// if none found.
func (m *PspConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *PspConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProviderCode

	// no validation rules for MethodType

	// no validation rules for PaymentCurrency

	// no validation rules for Metadata

	if len(errors) > 0 {
		return PspConfigMultiError(errors)
	}

	return nil
}

// PspConfigMultiError is an error wrapping multiple validation errors returned
// by PspConfig.ValidateAll() if the designated constraints aren't met.
type PspConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PspConfigMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PspConfigMultiError) AllErrors() []error { return m }

// PspConfigValidationError is the validation error returned by
// PspConfig.Validate if the designated constraints aren't met.
type PspConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PspConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PspConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PspConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PspConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PspConfigValidationError) ErrorName() string { return "PspConfigValidationError" }

// Error satisfies the builtin error interface
func (e PspConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPspConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PspConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PspConfigValidationError{}

// Validate checks the field values on CreateDepositRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateDepositRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateDepositRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateDepositRequestMultiError, or nil if none found.
func (m *CreateDepositRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateDepositRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetUserId()); err != nil {
		err = CreateDepositRequestValidationError{
			field:  "UserId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := AccountType_name[int32(m.GetDestType())]; !ok {
		err := CreateDepositRequestValidationError{
			field:  "DestType",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetDestId()) < 1 {
		err := CreateDepositRequestValidationError{
			field:  "DestId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_CreateDepositRequest_AmountUsd_Pattern.MatchString(m.GetAmountUsd()) {
		err := CreateDepositRequestValidationError{
			field:  "AmountUsd",
			reason: "value does not match regex pattern \"^[0-9]+(\\\\.[0-9]{1,6})?$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for OfferRate

	// no validation rules for PaymentAmount

	if m.GetPspConfig() == nil {
		err := CreateDepositRequestValidationError{
			field:  "PspConfig",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetPspConfig()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateDepositRequestValidationError{
					field:  "PspConfig",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateDepositRequestValidationError{
					field:  "PspConfig",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPspConfig()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateDepositRequestValidationError{
				field:  "PspConfig",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if utf8.RuneCountInString(m.GetIdempotencyKey()) < 1 {
		err := CreateDepositRequestValidationError{
			field:  "IdempotencyKey",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Mt5Login

	if all {
		switch v := interface{}(m.GetExpiresAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateDepositRequestValidationError{
					field:  "ExpiresAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateDepositRequestValidationError{
					field:  "ExpiresAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetExpiresAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateDepositRequestValidationError{
				field:  "ExpiresAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateDepositRequestMultiError(errors)
	}

	return nil
}

func (m *CreateDepositRequest) _validateUuid(uuid string) error {
	if matched := _finance_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// CreateDepositRequestMultiError is an error wrapping multiple validation
// errors returned by CreateDepositRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateDepositRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateDepositRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateDepositRequestMultiError) AllErrors() []error { return m }

// CreateDepositRequestValidationError is the validation error returned by
// CreateDepositRequest.Validate if the designated constraints aren't met.
type CreateDepositRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateDepositRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateDepositRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateDepositRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateDepositRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateDepositRequestValidationError) ErrorName() string {
	return "CreateDepositRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateDepositRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateDepositRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateDepositRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateDepositRequestValidationError{}

var _CreateDepositRequest_AmountUsd_Pattern = regexp.MustCompile("^[0-9]+(\\.[0-9]{1,6})?$")

// Validate checks the field values on CreateDepositResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateDepositResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateDepositResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateDepositResponseMultiError, or nil if none found.
func (m *CreateDepositResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateDepositResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TxnId

	// no validation rules for ReferenceId

	// no validation rules for QrCodeBase64

	// no validation rules for PaymentUrl

	// no validation rules for PspTransactionId

	// no validation rules for Status

	if len(errors) > 0 {
		return CreateDepositResponseMultiError(errors)
	}

	return nil
}

// CreateDepositResponseMultiError is an error wrapping multiple validation
// errors returned by CreateDepositResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateDepositResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateDepositResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateDepositResponseMultiError) AllErrors() []error { return m }

// CreateDepositResponseValidationError is the validation error returned by
// CreateDepositResponse.Validate if the designated constraints aren't met.
type CreateDepositResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateDepositResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateDepositResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateDepositResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateDepositResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateDepositResponseValidationError) ErrorName() string {
	return "CreateDepositResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateDepositResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateDepositResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateDepositResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateDepositResponseValidationError{}

// Validate checks the field values on CreateWithdrawRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateWithdrawRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateWithdrawRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateWithdrawRequestMultiError, or nil if none found.
func (m *CreateWithdrawRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateWithdrawRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetUserId()); err != nil {
		err = CreateWithdrawRequestValidationError{
			field:  "UserId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := AccountType_name[int32(m.GetSourceType())]; !ok {
		err := CreateWithdrawRequestValidationError{
			field:  "SourceType",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetSourceId()) < 1 {
		err := CreateWithdrawRequestValidationError{
			field:  "SourceId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_CreateWithdrawRequest_AmountUsd_Pattern.MatchString(m.GetAmountUsd()) {
		err := CreateWithdrawRequestValidationError{
			field:  "AmountUsd",
			reason: "value does not match regex pattern \"^[0-9]+(\\\\.[0-9]{1,6})?$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for BidRate

	// no validation rules for PayoutAmount

	// no validation rules for PaymentCurrency

	if m.GetPspConfig() == nil {
		err := CreateWithdrawRequestValidationError{
			field:  "PspConfig",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetPspConfig()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateWithdrawRequestValidationError{
					field:  "PspConfig",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateWithdrawRequestValidationError{
					field:  "PspConfig",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPspConfig()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateWithdrawRequestValidationError{
				field:  "PspConfig",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if utf8.RuneCountInString(m.GetIdempotencyKey()) < 1 {
		err := CreateWithdrawRequestValidationError{
			field:  "IdempotencyKey",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Mt5Login

	if all {
		switch v := interface{}(m.GetExpiresAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateWithdrawRequestValidationError{
					field:  "ExpiresAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateWithdrawRequestValidationError{
					field:  "ExpiresAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetExpiresAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateWithdrawRequestValidationError{
				field:  "ExpiresAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateWithdrawRequestMultiError(errors)
	}

	return nil
}

func (m *CreateWithdrawRequest) _validateUuid(uuid string) error {
	if matched := _finance_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// CreateWithdrawRequestMultiError is an error wrapping multiple validation
// errors returned by CreateWithdrawRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateWithdrawRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateWithdrawRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateWithdrawRequestMultiError) AllErrors() []error { return m }

// CreateWithdrawRequestValidationError is the validation error returned by
// CreateWithdrawRequest.Validate if the designated constraints aren't met.
type CreateWithdrawRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateWithdrawRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateWithdrawRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateWithdrawRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateWithdrawRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateWithdrawRequestValidationError) ErrorName() string {
	return "CreateWithdrawRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateWithdrawRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateWithdrawRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateWithdrawRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateWithdrawRequestValidationError{}

var _CreateWithdrawRequest_AmountUsd_Pattern = regexp.MustCompile("^[0-9]+(\\.[0-9]{1,6})?$")

// Validate checks the field values on CreateWithdrawResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateWithdrawResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateWithdrawResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateWithdrawResponseMultiError, or nil if none found.
func (m *CreateWithdrawResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateWithdrawResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TxnId

	// no validation rules for ReferenceId

	// no validation rules for Status

	if len(errors) > 0 {
		return CreateWithdrawResponseMultiError(errors)
	}

	return nil
}

// CreateWithdrawResponseMultiError is an error wrapping multiple validation
// errors returned by CreateWithdrawResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateWithdrawResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateWithdrawResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateWithdrawResponseMultiError) AllErrors() []error { return m }

// CreateWithdrawResponseValidationError is the validation error returned by
// CreateWithdrawResponse.Validate if the designated constraints aren't met.
type CreateWithdrawResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateWithdrawResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateWithdrawResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateWithdrawResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateWithdrawResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateWithdrawResponseValidationError) ErrorName() string {
	return "CreateWithdrawResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateWithdrawResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateWithdrawResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateWithdrawResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateWithdrawResponseValidationError{}

// Validate checks the field values on ApproveWithdrawRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ApproveWithdrawRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ApproveWithdrawRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ApproveWithdrawRequestMultiError, or nil if none found.
func (m *ApproveWithdrawRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ApproveWithdrawRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TxnId

	// no validation rules for AdminId

	if len(errors) > 0 {
		return ApproveWithdrawRequestMultiError(errors)
	}

	return nil
}

// ApproveWithdrawRequestMultiError is an error wrapping multiple validation
// errors returned by ApproveWithdrawRequest.ValidateAll() if the designated
// constraints aren't met.
type ApproveWithdrawRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ApproveWithdrawRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ApproveWithdrawRequestMultiError) AllErrors() []error { return m }

// ApproveWithdrawRequestValidationError is the validation error returned by
// ApproveWithdrawRequest.Validate if the designated constraints aren't met.
type ApproveWithdrawRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ApproveWithdrawRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ApproveWithdrawRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ApproveWithdrawRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ApproveWithdrawRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ApproveWithdrawRequestValidationError) ErrorName() string {
	return "ApproveWithdrawRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ApproveWithdrawRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sApproveWithdrawRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ApproveWithdrawRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ApproveWithdrawRequestValidationError{}

// Validate checks the field values on ApproveWithdrawResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ApproveWithdrawResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ApproveWithdrawResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ApproveWithdrawResponseMultiError, or nil if none found.
func (m *ApproveWithdrawResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ApproveWithdrawResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Status

	// no validation rules for PspTransactionId

	if len(errors) > 0 {
		return ApproveWithdrawResponseMultiError(errors)
	}

	return nil
}

// ApproveWithdrawResponseMultiError is an error wrapping multiple validation
// errors returned by ApproveWithdrawResponse.ValidateAll() if the designated
// constraints aren't met.
type ApproveWithdrawResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ApproveWithdrawResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ApproveWithdrawResponseMultiError) AllErrors() []error { return m }

// ApproveWithdrawResponseValidationError is the validation error returned by
// ApproveWithdrawResponse.Validate if the designated constraints aren't met.
type ApproveWithdrawResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ApproveWithdrawResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ApproveWithdrawResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ApproveWithdrawResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ApproveWithdrawResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ApproveWithdrawResponseValidationError) ErrorName() string {
	return "ApproveWithdrawResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ApproveWithdrawResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sApproveWithdrawResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ApproveWithdrawResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ApproveWithdrawResponseValidationError{}

// Validate checks the field values on RejectWithdrawRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RejectWithdrawRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RejectWithdrawRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RejectWithdrawRequestMultiError, or nil if none found.
func (m *RejectWithdrawRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RejectWithdrawRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TxnId

	// no validation rules for AdminId

	// no validation rules for Reason

	if len(errors) > 0 {
		return RejectWithdrawRequestMultiError(errors)
	}

	return nil
}

// RejectWithdrawRequestMultiError is an error wrapping multiple validation
// errors returned by RejectWithdrawRequest.ValidateAll() if the designated
// constraints aren't met.
type RejectWithdrawRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RejectWithdrawRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RejectWithdrawRequestMultiError) AllErrors() []error { return m }

// RejectWithdrawRequestValidationError is the validation error returned by
// RejectWithdrawRequest.Validate if the designated constraints aren't met.
type RejectWithdrawRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RejectWithdrawRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RejectWithdrawRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RejectWithdrawRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RejectWithdrawRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RejectWithdrawRequestValidationError) ErrorName() string {
	return "RejectWithdrawRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RejectWithdrawRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRejectWithdrawRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RejectWithdrawRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RejectWithdrawRequestValidationError{}

// Validate checks the field values on RefundWithdrawRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RefundWithdrawRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RefundWithdrawRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RefundWithdrawRequestMultiError, or nil if none found.
func (m *RefundWithdrawRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RefundWithdrawRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TxnId

	// no validation rules for AdminId

	// no validation rules for Reason

	if len(errors) > 0 {
		return RefundWithdrawRequestMultiError(errors)
	}

	return nil
}

// RefundWithdrawRequestMultiError is an error wrapping multiple validation
// errors returned by RefundWithdrawRequest.ValidateAll() if the designated
// constraints aren't met.
type RefundWithdrawRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RefundWithdrawRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RefundWithdrawRequestMultiError) AllErrors() []error { return m }

// RefundWithdrawRequestValidationError is the validation error returned by
// RefundWithdrawRequest.Validate if the designated constraints aren't met.
type RefundWithdrawRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RefundWithdrawRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RefundWithdrawRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RefundWithdrawRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RefundWithdrawRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RefundWithdrawRequestValidationError) ErrorName() string {
	return "RefundWithdrawRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RefundWithdrawRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRefundWithdrawRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RefundWithdrawRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RefundWithdrawRequestValidationError{}

// Validate checks the field values on CreateTransferRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateTransferRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateTransferRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateTransferRequestMultiError, or nil if none found.
func (m *CreateTransferRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateTransferRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetUserId()); err != nil {
		err = CreateTransferRequestValidationError{
			field:  "UserId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := AccountType_name[int32(m.GetSourceType())]; !ok {
		err := CreateTransferRequestValidationError{
			field:  "SourceType",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetSourceId()) < 1 {
		err := CreateTransferRequestValidationError{
			field:  "SourceId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := AccountType_name[int32(m.GetDestType())]; !ok {
		err := CreateTransferRequestValidationError{
			field:  "DestType",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetDestId()) < 1 {
		err := CreateTransferRequestValidationError{
			field:  "DestId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_CreateTransferRequest_AmountUsd_Pattern.MatchString(m.GetAmountUsd()) {
		err := CreateTransferRequestValidationError{
			field:  "AmountUsd",
			reason: "value does not match regex pattern \"^[0-9]+(\\\\.[0-9]{1,6})?$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetIdempotencyKey()) < 1 {
		err := CreateTransferRequestValidationError{
			field:  "IdempotencyKey",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateTransferRequestMultiError(errors)
	}

	return nil
}

func (m *CreateTransferRequest) _validateUuid(uuid string) error {
	if matched := _finance_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// CreateTransferRequestMultiError is an error wrapping multiple validation
// errors returned by CreateTransferRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateTransferRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateTransferRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateTransferRequestMultiError) AllErrors() []error { return m }

// CreateTransferRequestValidationError is the validation error returned by
// CreateTransferRequest.Validate if the designated constraints aren't met.
type CreateTransferRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateTransferRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateTransferRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateTransferRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateTransferRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateTransferRequestValidationError) ErrorName() string {
	return "CreateTransferRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateTransferRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateTransferRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateTransferRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateTransferRequestValidationError{}

var _CreateTransferRequest_AmountUsd_Pattern = regexp.MustCompile("^[0-9]+(\\.[0-9]{1,6})?$")

// Validate checks the field values on CreateTransferResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateTransferResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateTransferResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateTransferResponseMultiError, or nil if none found.
func (m *CreateTransferResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateTransferResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TxnId

	// no validation rules for Status

	if len(errors) > 0 {
		return CreateTransferResponseMultiError(errors)
	}

	return nil
}

// CreateTransferResponseMultiError is an error wrapping multiple validation
// errors returned by CreateTransferResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateTransferResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateTransferResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateTransferResponseMultiError) AllErrors() []error { return m }

// CreateTransferResponseValidationError is the validation error returned by
// CreateTransferResponse.Validate if the designated constraints aren't met.
type CreateTransferResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateTransferResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateTransferResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateTransferResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateTransferResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateTransferResponseValidationError) ErrorName() string {
	return "CreateTransferResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateTransferResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateTransferResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateTransferResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateTransferResponseValidationError{}
