// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/finance/v1/finance.proto

package financev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PSP config resolved by CRM, passed per-request
type PspConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProviderCode    string                 `protobuf:"bytes,1,opt,name=provider_code,json=providerCode,proto3" json:"provider_code,omitempty"`
	MethodType      string                 `protobuf:"bytes,2,opt,name=method_type,json=methodType,proto3" json:"method_type,omitempty"`
	PaymentCurrency string                 `protobuf:"bytes,3,opt,name=payment_currency,json=paymentCurrency,proto3" json:"payment_currency,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PspConfig) Reset() {
	*x = PspConfig{}
	mi := &file_proto_finance_v1_finance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PspConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PspConfig) ProtoMessage() {}

func (x *PspConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finance_v1_finance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PspConfig.ProtoReflect.Descriptor instead.
func (*PspConfig) Descriptor() ([]byte, []int) {
	return file_proto_finance_v1_finance_proto_rawDescGZIP(), []int{0}
}

func (x *PspConfig) GetProviderCode() string {
	if x != nil {
		return x.ProviderCode
	}
	return ""
}

func (x *PspConfig) GetMethodType() string {
	if x != nil {
		return x.MethodType
	}
	return ""
}

func (x *PspConfig) GetPaymentCurrency() string {
	if x != nil {
		return x.PaymentCurrency
	}
	return ""
}

func (x *PspConfig) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// --- Deposit ---
type CreateDepositRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DestType       string                 `protobuf:"bytes,2,opt,name=dest_type,json=destType,proto3" json:"dest_type,omitempty"` // TRADING | WALLET
	DestId         string                 `protobuf:"bytes,3,opt,name=dest_id,json=destId,proto3" json:"dest_id,omitempty"`
	AmountUsd      string                 `protobuf:"bytes,4,opt,name=amount_usd,json=amountUsd,proto3" json:"amount_usd,omitempty"`
	OfferRate      string                 `protobuf:"bytes,5,opt,name=offer_rate,json=offerRate,proto3" json:"offer_rate,omitempty"`
	PaymentAmount  string                 `protobuf:"bytes,6,opt,name=payment_amount,json=paymentAmount,proto3" json:"payment_amount,omitempty"`
	PspConfig      *PspConfig             `protobuf:"bytes,7,opt,name=psp_config,json=pspConfig,proto3" json:"psp_config,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,8,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Mt5Login       int64                  `protobuf:"varint,9,opt,name=mt5_login,json=mt5Login,proto3" json:"mt5_login,omitempty"`
	ExpiresAt      string                 `protobuf:"bytes,10,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateDepositRequest) Reset() {
	*x = CreateDepositRequest{}
	mi := &file_proto_finance_v1_finance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDepositRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDepositRequest) ProtoMessage() {}

func (x *CreateDepositRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finance_v1_finance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDepositRequest.ProtoReflect.Descriptor instead.
func (*CreateDepositRequest) Descriptor() ([]byte, []int) {
	return file_proto_finance_v1_finance_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDepositRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateDepositRequest) GetDestType() string {
	if x != nil {
		return x.DestType
	}
	return ""
}

func (x *CreateDepositRequest) GetDestId() string {
	if x != nil {
		return x.DestId
	}
	return ""
}

func (x *CreateDepositRequest) GetAmountUsd() string {
	if x != nil {
		return x.AmountUsd
	}
	return ""
}

func (x *CreateDepositRequest) GetOfferRate() string {
	if x != nil {
		return x.OfferRate
	}
	return ""
}

func (x *CreateDepositRequest) GetPaymentAmount() string {
	if x != nil {
		return x.PaymentAmount
	}
	return ""
}

func (x *CreateDepositRequest) GetPspConfig() *PspConfig {
	if x != nil {
		return x.PspConfig
	}
	return nil
}

func (x *CreateDepositRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreateDepositRequest) GetMt5Login() int64 {
	if x != nil {
		return x.Mt5Login
	}
	return 0
}

func (x *CreateDepositRequest) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type CreateDepositResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TxnId            string                 `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	ReferenceId      string                 `protobuf:"bytes,2,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	QrCodeBase64     string                 `protobuf:"bytes,3,opt,name=qr_code_base64,json=qrCodeBase64,proto3" json:"qr_code_base64,omitempty"`
	PaymentUrl       string                 `protobuf:"bytes,4,opt,name=payment_url,json=paymentUrl,proto3" json:"payment_url,omitempty"`
	PspTransactionId string                 `protobuf:"bytes,5,opt,name=psp_transaction_id,json=pspTransactionId,proto3" json:"psp_transaction_id,omitempty"`
	Status           string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateDepositResponse) Reset() {
	*x = CreateDepositResponse{}
	mi := &file_proto_finance_v1_finance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDepositResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDepositResponse) ProtoMessage() {}

func (x *CreateDepositResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finance_v1_finance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDepositResponse.ProtoReflect.Descriptor instead.
func (*CreateDepositResponse) Descriptor() ([]byte, []int) {
	return file_proto_finance_v1_finance_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDepositResponse) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

func (x *CreateDepositResponse) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *CreateDepositResponse) GetQrCodeBase64() string {
	if x != nil {
		return x.QrCodeBase64
	}
	return ""
}

func (x *CreateDepositResponse) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

func (x *CreateDepositResponse) GetPspTransactionId() string {
	if x != nil {
		return x.PspTransactionId
	}
	return ""
}

func (x *CreateDepositResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// --- Withdraw ---
type CreateWithdrawRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SourceType      string                 `protobuf:"bytes,2,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	SourceId        string                 `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	AmountUsd       string                 `protobuf:"bytes,4,opt,name=amount_usd,json=amountUsd,proto3" json:"amount_usd,omitempty"`
	BidRate         string                 `protobuf:"bytes,5,opt,name=bid_rate,json=bidRate,proto3" json:"bid_rate,omitempty"`
	PayoutAmount    string                 `protobuf:"bytes,6,opt,name=payout_amount,json=payoutAmount,proto3" json:"payout_amount,omitempty"`
	PaymentCurrency string                 `protobuf:"bytes,7,opt,name=payment_currency,json=paymentCurrency,proto3" json:"payment_currency,omitempty"`
	PspConfig       *PspConfig             `protobuf:"bytes,8,opt,name=psp_config,json=pspConfig,proto3" json:"psp_config,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,9,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Mt5Login        int64                  `protobuf:"varint,10,opt,name=mt5_login,json=mt5Login,proto3" json:"mt5_login,omitempty"`
	ExpiresAt       string                 `protobuf:"bytes,11,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateWithdrawRequest) Reset() {
	*x = CreateWithdrawRequest{}
	mi := &file_proto_finance_v1_finance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWithdrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWithdrawRequest) ProtoMessage() {}

func (x *CreateWithdrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finance_v1_finance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWithdrawRequest.ProtoReflect.Descriptor instead.
func (*CreateWithdrawRequest) Descriptor() ([]byte, []int) {
	return file_proto_finance_v1_finance_proto_rawDescGZIP(), []int{3}
}

func (x *CreateWithdrawRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateWithdrawRequest) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *CreateWithdrawRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *CreateWithdrawRequest) GetAmountUsd() string {
	if x != nil {
		return x.AmountUsd
	}
	return ""
}

func (x *CreateWithdrawRequest) GetBidRate() string {
	if x != nil {
		return x.BidRate
	}
	return ""
}

func (x *CreateWithdrawRequest) GetPayoutAmount() string {
	if x != nil {
		return x.PayoutAmount
	}
	return ""
}

func (x *CreateWithdrawRequest) GetPaymentCurrency() string {
	if x != nil {
		return x.PaymentCurrency
	}
	return ""
}

func (x *CreateWithdrawRequest) GetPspConfig() *PspConfig {
	if x != nil {
		return x.PspConfig
	}
	return nil
}

func (x *CreateWithdrawRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreateWithdrawRequest) GetMt5Login() int64 {
	if x != nil {
		return x.Mt5Login
	}
	return 0
}

func (x *CreateWithdrawRequest) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type CreateWithdrawResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxnId         string                 `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,2,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWithdrawResponse) Reset() {
	*x = CreateWithdrawResponse{}
	mi := &file_proto_finance_v1_finance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWithdrawResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWithdrawResponse) ProtoMessage() {}

func (x *CreateWithdrawResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finance_v1_finance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWithdrawResponse.ProtoReflect.Descriptor instead.
func (*CreateWithdrawResponse) Descriptor() ([]byte, []int) {
	return file_proto_finance_v1_finance_proto_rawDescGZIP(), []int{4}
}

func (x *CreateWithdrawResponse) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

func (x *CreateWithdrawResponse) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *CreateWithdrawResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ApproveWithdrawRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxnId         string                 `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	AdminId       string                 `protobuf:"bytes,2,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveWithdrawRequest) Reset() {
	*x = ApproveWithdrawRequest{}
	mi := &file_proto_finance_v1_finance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveWithdrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveWithdrawRequest) ProtoMessage() {}

func (x *ApproveWithdrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finance_v1_finance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveWithdrawRequest.ProtoReflect.Descriptor instead.
func (*ApproveWithdrawRequest) Descriptor() ([]byte, []int) {
	return file_proto_finance_v1_finance_proto_rawDescGZIP(), []int{5}
}

func (x *ApproveWithdrawRequest) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

func (x *ApproveWithdrawRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

type ApproveWithdrawResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Status           string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // COMPLETED | PROCESSING | FAILED
	PspTransactionId string                 `protobuf:"bytes,2,opt,name=psp_transaction_id,json=pspTransactionId,proto3" json:"psp_transaction_id,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ApproveWithdrawResponse) Reset() {
	*x = ApproveWithdrawResponse{}
	mi := &file_proto_finance_v1_finance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveWithdrawResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveWithdrawResponse) ProtoMessage() {}

func (x *ApproveWithdrawResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finance_v1_finance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveWithdrawResponse.ProtoReflect.Descriptor instead.
func (*ApproveWithdrawResponse) Descriptor() ([]byte, []int) {
	return file_proto_finance_v1_finance_proto_rawDescGZIP(), []int{6}
}

func (x *ApproveWithdrawResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApproveWithdrawResponse) GetPspTransactionId() string {
	if x != nil {
		return x.PspTransactionId
	}
	return ""
}

func (x *ApproveWithdrawResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type RejectWithdrawRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxnId         string                 `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	AdminId       string                 `protobuf:"bytes,2,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectWithdrawRequest) Reset() {
	*x = RejectWithdrawRequest{}
	mi := &file_proto_finance_v1_finance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectWithdrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectWithdrawRequest) ProtoMessage() {}

func (x *RejectWithdrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finance_v1_finance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectWithdrawRequest.ProtoReflect.Descriptor instead.
func (*RejectWithdrawRequest) Descriptor() ([]byte, []int) {
	return file_proto_finance_v1_finance_proto_rawDescGZIP(), []int{7}
}

func (x *RejectWithdrawRequest) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

func (x *RejectWithdrawRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

func (x *RejectWithdrawRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RefundWithdrawRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxnId         string                 `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	AdminId       string                 `protobuf:"bytes,2,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundWithdrawRequest) Reset() {
	*x = RefundWithdrawRequest{}
	mi := &file_proto_finance_v1_finance_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundWithdrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundWithdrawRequest) ProtoMessage() {}

func (x *RefundWithdrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finance_v1_finance_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundWithdrawRequest.ProtoReflect.Descriptor instead.
func (*RefundWithdrawRequest) Descriptor() ([]byte, []int) {
	return file_proto_finance_v1_finance_proto_rawDescGZIP(), []int{8}
}

func (x *RefundWithdrawRequest) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

func (x *RefundWithdrawRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

func (x *RefundWithdrawRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_finance_v1_finance_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finance_v1_finance_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_finance_v1_finance_proto_rawDescGZIP(), []int{9}
}

func (x *StatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// --- Internal Transfer ---
type CreateTransferRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SourceType     string                 `protobuf:"bytes,2,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	SourceId       string                 `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	DestType       string                 `protobuf:"bytes,4,opt,name=dest_type,json=destType,proto3" json:"dest_type,omitempty"`
	DestId         string                 `protobuf:"bytes,5,opt,name=dest_id,json=destId,proto3" json:"dest_id,omitempty"`
	AmountUsd      string                 `protobuf:"bytes,6,opt,name=amount_usd,json=amountUsd,proto3" json:"amount_usd,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,7,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateTransferRequest) Reset() {
	*x = CreateTransferRequest{}
	mi := &file_proto_finance_v1_finance_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransferRequest) ProtoMessage() {}

func (x *CreateTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finance_v1_finance_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransferRequest.ProtoReflect.Descriptor instead.
func (*CreateTransferRequest) Descriptor() ([]byte, []int) {
	return file_proto_finance_v1_finance_proto_rawDescGZIP(), []int{10}
}

func (x *CreateTransferRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateTransferRequest) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *CreateTransferRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *CreateTransferRequest) GetDestType() string {
	if x != nil {
		return x.DestType
	}
	return ""
}

func (x *CreateTransferRequest) GetDestId() string {
	if x != nil {
		return x.DestId
	}
	return ""
}

func (x *CreateTransferRequest) GetAmountUsd() string {
	if x != nil {
		return x.AmountUsd
	}
	return ""
}

func (x *CreateTransferRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type CreateTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxnId         string                 `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransferResponse) Reset() {
	*x = CreateTransferResponse{}
	mi := &file_proto_finance_v1_finance_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransferResponse) ProtoMessage() {}

func (x *CreateTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finance_v1_finance_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransferResponse.ProtoReflect.Descriptor instead.
func (*CreateTransferResponse) Descriptor() ([]byte, []int) {
	return file_proto_finance_v1_finance_proto_rawDescGZIP(), []int{11}
}

func (x *CreateTransferResponse) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

func (x *CreateTransferResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_finance_v1_finance_proto protoreflect.FileDescriptor

const file_proto_finance_v1_finance_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/finance/v1/finance.proto\x12\n" +
	"finance.v1\"\xfa\x01\n" +
	"\tPspConfig\x12#\n" +
	"\rprovider_code\x18\x01 \x01(\tR\fproviderCode\x12\x1f\n" +
	"\vmethod_type\x18\x02 \x01(\tR\n" +
	"methodType\x12)\n" +
	"\x10payment_currency\x18\x03 \x01(\tR\x0fpaymentCurrency\x12?\n" +
	"\bmetadata\x18\x04 \x03(\v2#.finance.v1.PspConfig.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe5\x02\n" +
	"\x14CreateDepositRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdest_type\x18\x02 \x01(\tR\bdestType\x12\x17\n" +
	"\adest_id\x18\x03 \x01(\tR\x06destId\x12\x1d\n" +
	"\n" +
	"amount_usd\x18\x04 \x01(\tR\tamountUsd\x12\x1d\n" +
	"\n" +
	"offer_rate\x18\x05 \x01(\tR\tofferRate\x12%\n" +
	"\x0epayment_amount\x18\x06 \x01(\tR\rpaymentAmount\x124\n" +
	"\n" +
	"psp_config\x18\a \x01(\v2\x15.finance.v1.PspConfigR\tpspConfig\x12'\n" +
	"\x0fidempotency_key\x18\b \x01(\tR\x0eidempotencyKey\x12\x1b\n" +
	"\tmt5_login\x18\t \x01(\x03R\bmt5Login\x12\x1d\n" +
	"\n" +
	"expires_at\x18\n" +
	" \x01(\tR\texpiresAt\"\xde\x01\n" +
	"\x15CreateDepositResponse\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\tR\x05txnId\x12!\n" +
	"\freference_id\x18\x02 \x01(\tR\vreferenceId\x12$\n" +
	"\x0eqr_code_base64\x18\x03 \x01(\tR\fqrCodeBase64\x12\x1f\n" +
	"\vpayment_url\x18\x04 \x01(\tR\n" +
	"paymentUrl\x12,\n" +
	"\x12psp_transaction_id\x18\x05 \x01(\tR\x10pspTransactionId\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\x93\x03\n" +
	"\x15CreateWithdrawRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vsource_type\x18\x02 \x01(\tR\n" +
	"sourceType\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\tR\bsourceId\x12\x1d\n" +
	"\n" +
	"amount_usd\x18\x04 \x01(\tR\tamountUsd\x12\x19\n" +
	"\bbid_rate\x18\x05 \x01(\tR\abidRate\x12#\n" +
	"\rpayout_amount\x18\x06 \x01(\tR\fpayoutAmount\x12)\n" +
	"\x10payment_currency\x18\a \x01(\tR\x0fpaymentCurrency\x124\n" +
	"\n" +
	"psp_config\x18\b \x01(\v2\x15.finance.v1.PspConfigR\tpspConfig\x12'\n" +
	"\x0fidempotency_key\x18\t \x01(\tR\x0eidempotencyKey\x12\x1b\n" +
	"\tmt5_login\x18\n" +
	" \x01(\x03R\bmt5Login\x12\x1d\n" +
	"\n" +
	"expires_at\x18\v \x01(\tR\texpiresAt\"j\n" +
	"\x16CreateWithdrawResponse\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\tR\x05txnId\x12!\n" +
	"\freference_id\x18\x02 \x01(\tR\vreferenceId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"J\n" +
	"\x16ApproveWithdrawRequest\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\tR\x05txnId\x12\x19\n" +
	"\badmin_id\x18\x02 \x01(\tR\aadminId\"\x84\x01\n" +
	"\x17ApproveWithdrawResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12,\n" +
	"\x12psp_transaction_id\x18\x02 \x01(\tR\x10pspTransactionId\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"a\n" +
	"\x15RejectWithdrawRequest\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\tR\x05txnId\x12\x19\n" +
	"\badmin_id\x18\x02 \x01(\tR\aadminId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"a\n" +
	"\x15RefundWithdrawRequest\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\tR\x05txnId\x12\x19\n" +
	"\badmin_id\x18\x02 \x01(\tR\aadminId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"D\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xec\x01\n" +
	"\x15CreateTransferRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vsource_type\x18\x02 \x01(\tR\n" +
	"sourceType\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\tR\bsourceId\x12\x1b\n" +
	"\tdest_type\x18\x04 \x01(\tR\bdestType\x12\x17\n" +
	"\adest_id\x18\x05 \x01(\tR\x06destId\x12\x1d\n" +
	"\n" +
	"amount_usd\x18\x06 \x01(\tR\tamountUsd\x12'\n" +
	"\x0fidempotency_key\x18\a \x01(\tR\x0eidempotencyKey\"G\n" +
	"\x16CreateTransferResponse\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\tR\x05txnId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\x96\x04\n" +
	"\x0eFinanceService\x12T\n" +
	"\rCreateDeposit\x12 .finance.v1.CreateDepositRequest\x1a!.finance.v1.CreateDepositResponse\x12W\n" +
	"\x0eCreateWithdraw\x12!.finance.v1.CreateWithdrawRequest\x1a\".finance.v1.CreateWithdrawResponse\x12Z\n" +
	"\x0fApproveWithdraw\x12\".finance.v1.ApproveWithdrawRequest\x1a#.finance.v1.ApproveWithdrawResponse\x12O\n" +
	"\x0eRejectWithdraw\x12!.finance.v1.RejectWithdrawRequest\x1a\x1a.finance.v1.StatusResponse\x12O\n" +
	"\x0eRefundWithdraw\x12!.finance.v1.RefundWithdrawRequest\x1a\x1a.finance.v1.StatusResponse\x12W\n" +
	"\x0eCreateTransfer\x12!.finance.v1.CreateTransferRequest\x1a\".finance.v1.CreateTransferResponseB?Z=github.com/samsonnaze5/aeternixth-go-lib/finance/v1;financev1b\x06proto3"

var (
	file_proto_finance_v1_finance_proto_rawDescOnce sync.Once
	file_proto_finance_v1_finance_proto_rawDescData []byte
)

func file_proto_finance_v1_finance_proto_rawDescGZIP() []byte {
	file_proto_finance_v1_finance_proto_rawDescOnce.Do(func() {
		file_proto_finance_v1_finance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_finance_v1_finance_proto_rawDesc), len(file_proto_finance_v1_finance_proto_rawDesc)))
	})
	return file_proto_finance_v1_finance_proto_rawDescData
}

var file_proto_finance_v1_finance_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_finance_v1_finance_proto_goTypes = []any{
	(*PspConfig)(nil),               // 0: finance.v1.PspConfig
	(*CreateDepositRequest)(nil),    // 1: finance.v1.CreateDepositRequest
	(*CreateDepositResponse)(nil),   // 2: finance.v1.CreateDepositResponse
	(*CreateWithdrawRequest)(nil),   // 3: finance.v1.CreateWithdrawRequest
	(*CreateWithdrawResponse)(nil),  // 4: finance.v1.CreateWithdrawResponse
	(*ApproveWithdrawRequest)(nil),  // 5: finance.v1.ApproveWithdrawRequest
	(*ApproveWithdrawResponse)(nil), // 6: finance.v1.ApproveWithdrawResponse
	(*RejectWithdrawRequest)(nil),   // 7: finance.v1.RejectWithdrawRequest
	(*RefundWithdrawRequest)(nil),   // 8: finance.v1.RefundWithdrawRequest
	(*StatusResponse)(nil),          // 9: finance.v1.StatusResponse
	(*CreateTransferRequest)(nil),   // 10: finance.v1.CreateTransferRequest
	(*CreateTransferResponse)(nil),  // 11: finance.v1.CreateTransferResponse
	nil,                             // 12: finance.v1.PspConfig.MetadataEntry
}
var file_proto_finance_v1_finance_proto_depIdxs = []int32{
	12, // 0: finance.v1.PspConfig.metadata:type_name -> finance.v1.PspConfig.MetadataEntry
	0,  // 1: finance.v1.CreateDepositRequest.psp_config:type_name -> finance.v1.PspConfig
	0,  // 2: finance.v1.CreateWithdrawRequest.psp_config:type_name -> finance.v1.PspConfig
	1,  // 3: finance.v1.FinanceService.CreateDeposit:input_type -> finance.v1.CreateDepositRequest
	3,  // 4: finance.v1.FinanceService.CreateWithdraw:input_type -> finance.v1.CreateWithdrawRequest
	5,  // 5: finance.v1.FinanceService.ApproveWithdraw:input_type -> finance.v1.ApproveWithdrawRequest
	7,  // 6: finance.v1.FinanceService.RejectWithdraw:input_type -> finance.v1.RejectWithdrawRequest
	8,  // 7: finance.v1.FinanceService.RefundWithdraw:input_type -> finance.v1.RefundWithdrawRequest
	10, // 8: finance.v1.FinanceService.CreateTransfer:input_type -> finance.v1.CreateTransferRequest
	2,  // 9: finance.v1.FinanceService.CreateDeposit:output_type -> finance.v1.CreateDepositResponse
	4,  // 10: finance.v1.FinanceService.CreateWithdraw:output_type -> finance.v1.CreateWithdrawResponse
	6,  // 11: finance.v1.FinanceService.ApproveWithdraw:output_type -> finance.v1.ApproveWithdrawResponse
	9,  // 12: finance.v1.FinanceService.RejectWithdraw:output_type -> finance.v1.StatusResponse
	9,  // 13: finance.v1.FinanceService.RefundWithdraw:output_type -> finance.v1.StatusResponse
	11, // 14: finance.v1.FinanceService.CreateTransfer:output_type -> finance.v1.CreateTransferResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_finance_v1_finance_proto_init() }
func file_proto_finance_v1_finance_proto_init() {
	if File_proto_finance_v1_finance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_finance_v1_finance_proto_rawDesc), len(file_proto_finance_v1_finance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_finance_v1_finance_proto_goTypes,
		DependencyIndexes: file_proto_finance_v1_finance_proto_depIdxs,
		MessageInfos:      file_proto_finance_v1_finance_proto_msgTypes,
	}.Build()
	File_proto_finance_v1_finance_proto = out.File
	file_proto_finance_v1_finance_proto_goTypes = nil
	file_proto_finance_v1_finance_proto_depIdxs = nil
}
